[package]
name = "oxen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = { version = "3.1.0", features = ["cargo"] }
indicatif = "0.16.2"
jwalk = "0.6.0"
rayon = "1.5.1"
reqwest = { version = "0.11.9", features = ["blocking", "multipart", "json"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
serde_derive = "1.0"
sha2 = "0.10.1"
toml = "0.5.8"
futures = "0.3"
signal-hook = "0.3.13"
rpassword = "6.0"
dirs = "4.0.0"
urlencoding = "2.1.0"
http = "0.2.6"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
colored = "2.0.0"
rocksdb = { version = "0.18.0", default-features = false, features = ["lz4"] }
actix-web = { version = "4", features = ["openssl"] }
openssl = { version = "0.10" }
dotenv = "0.9.0"
flate2 = "1.0.23"
tar = "0.4.38"
walkdir = "2"

[profile.release]
codegen-units = 1

[lib]
name = "liboxen"
path = "src/lib.rs"

[[bin]]
name = "oxen"
path = "src/oxen.rs"

[[bin]]
name = "oxen-server"
path = "src/server.rs"
