//! `Box<Box<T>>`: the outer type is `Box<Box<T>>` (its own impl) and the
//! syntactic inner is `Box<T>` (a path-shaped, sized type). The macro
//! generates impls for both layers — but **not** for the deepest `T`, since
//! the macro only unboxes one level.
//!
//! In practice, this means a caller with a `Box<i32>` value can produce the
//! variant directly (re-boxed once into `Box<Box<i32>>`); a caller with a
//! bare `i32` would need to box once before calling.

mod error {
    pub trait IntoOxenError {
        fn into_oxen(self) -> super::Nested;
    }
}

#[derive(Debug, oxen_macros::IntoOxen)]
#[allow(dead_code)]
pub enum Nested {
    Doubled(#[from_ox] Box<Box<i32>>),
}

#[test]
fn outer_double_box_works() {
    use error::IntoOxenError;
    let v: Box<Box<i32>> = Box::new(Box::new(11));
    let n: Nested = v.into_oxen();
    match n {
        Nested::Doubled(bb) => assert_eq!(**bb, 11),
    }
}

#[test]
fn one_level_unboxing_works() {
    use error::IntoOxenError;
    // `Box<i32>` is the syntactic inner, so the unbox-impl re-boxes it into
    // `Box<Box<i32>>` on construction.
    let v: Box<i32> = Box::new(22);
    let n: Nested = v.into_oxen();
    match n {
        Nested::Doubled(bb) => assert_eq!(**bb, 22),
    }
}

#[test]
fn deepest_t_does_not_get_an_impl() {
    // `i32` is the *deepest* inner, two boxes down. The macro only unboxes
    // one level, so a bare `i32` must NOT have an `IntoOxenError for i32`
    // generated by *this* enum's derive.
    //
    // We can't `assert!(impl_does_not_exist::<i32>())` directly, but we can
    // demonstrate that the only way to construct a `Nested` from a bare `i32`
    // is to manually wrap it. That's the documented contract.
    let n: Nested = Nested::Doubled(Box::new(Box::new(33)));
    match n {
        Nested::Doubled(bb) => assert_eq!(**bb, 33),
    }
}
