//! `Box<Box<T>>`: the outer type is `Box<Box<T>>` (its own impl) and the
//! syntactic inner is `Box<T>` (a path-shaped, sized type). The macro
//! generates impls for both layers — but **not** for the deepest `T`, since
//! the macro only unboxes one level.
//!
//! In practice, this means a caller with a `Box<Inner>` value can produce the
//! variant directly (re-boxed once into `Box<Box<Inner>>`); a caller with a
//! bare `Inner` would need to box once before calling.

mod error {
    pub trait IntoOxenError {
        fn into_oxen(self) -> super::Nested;
    }
}

#[derive(thiserror::Error, Debug)]
#[error("Inner({0})")]
pub struct Inner(pub i32);

#[oxen_macros::from_ox]
#[derive(thiserror::Error, Debug)]
#[allow(dead_code)]
pub enum Nested {
    #[error("doubled: {0:?}")]
    Doubled(#[from_ox] Box<Box<Inner>>),
}

#[test]
fn outer_double_box_works() {
    use error::IntoOxenError;
    let v: Box<Box<Inner>> = Box::new(Box::new(Inner(11)));
    let n: Nested = v.into_oxen();
    match n {
        Nested::Doubled(bb) => assert_eq!((**bb).0, 11),
    }
}

#[test]
fn one_level_unboxing_works() {
    use error::IntoOxenError;
    // `Box<Inner>` is the syntactic inner, so the unbox-impl re-boxes it into
    // `Box<Box<Inner>>` on construction.
    let v: Box<Inner> = Box::new(Inner(22));
    let n: Nested = v.into_oxen();
    match n {
        Nested::Doubled(bb) => assert_eq!((**bb).0, 22),
    }
}

#[test]
fn deepest_t_does_not_get_an_impl() {
    // `Inner` is the *deepest* inner, two boxes down. The macro only unboxes
    // one level, so a bare `Inner` must NOT have an `IntoOxenError for Inner`
    // generated by *this* enum's macro.
    //
    // The only way to construct a `Nested` from a bare `Inner` is to manually
    // wrap it twice — that's the documented contract.
    let n: Nested = Nested::Doubled(Box::new(Box::new(Inner(33))));
    match n {
        Nested::Doubled(bb) => assert_eq!((**bb).0, 33),
    }
}

// Strict negative check: the macro must only unbox one level. Today we have
// `IntoOxenError for Box<Box<Inner>>` (outer) and `IntoOxenError for Box<Inner>`
// (one-level-unboxed), but the deepest `Inner` must NOT have an impl. If a
// future change made the macro recurse, this assertion would fail to compile.
static_assertions::assert_not_impl_any!(Inner: error::IntoOxenError);
