[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "oxenai"
description = "Data version control for machine learning"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numpy>=2.0.0",
    "opencv-python-headless==4.10.0.84",
    "pandas>=2.0.1",
    "polars>=1.15.0",
    "pyarrow>=18.0.0",
    "requests>=2.32.3",
    "toml==0.10.2",
    "tqdm>=4.67.1",
]



[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]

