on:
  push:
    branches:
      - monorepo

name: 🐂 Continuous integration

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/ci_lint.yml

  oxen-rust-tests:
    name: oxen-rust tests
    uses: ./.github/workflows/ci_tests_oxen_rust.yml

  oxen-python-tests:
    name: oxen-python tests
    uses: ./.github/workflows/ci_tests_oxen_python.yml
