name: 🐂🔎 Continuous integration - Lint

on:
  workflow_call:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  check:
    name: Cargo check, format, clippy + Ruff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: clippy, rustfmt

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          # Only cache builds from main. Otherwise our caches will be too big and start to churn. (10 GB limit in GitHub Actions)
          # Other branches will still use the cache but won't save it.
          save-if: ${{ github.ref == 'refs/heads/main' }}
          workspaces: "."

      - name: Install dependencies and development tools
        run: |
          cd ${{ github.workspace }}
          ./bin/install-prereqs

      - name: Run Pre-Commit Hooks
        run: |
          cd ${{ github.workspace }}
          if ! pre-commit run --color=always --verbose --all-files ; then
            echo "Pre-commit failed. Showing git status:"
            git -c color.status=always status
            exit 1
          fi
