name: Python Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $GITHUB_WORKSPACE/oxen

    steps:
    - uses: actions/checkout@v3

    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "Oxen-AI/Oxen"
        latest: true
        fileName: "oxen-server-ubuntu-22.04.deb"
        out-file-path: "oxen-server"

    - name: Install oxen-server
      run: |
        sudo dpkg -i $GITHUB_WORKSPACE/oxen/oxen-server/oxen-server-ubuntu-22.04.deb

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maturin
        pip install pytest
        pip install -e .

    - name: Run Tests
      run: |
        oxen-server start &
        pytest -s tests


